### ISSUE TITLE
0 13 * * 1 (verbose: true)

### ISSUE THREAD

**Issue by nhusher** [bradyholt/cRonstrue#105]
Thanks for this library, it's exactly what I need. Fiddling with options, I found:

```js
cronstrue.toString('0 13 * * 1', { verbose: true })
```

Renders as, "At 01:00 PM, every day, only on Monday"

**Comment by deyko** [comment]
Hello Brady! Thank you very much for this library, it has been very helpful!

When I've been using it, I've realized what could be a mistake.

If you create a cron for the day Wednesday, Tuesday or Sunday, there is no problem, the library returns the correct message, however, if you create it for Monday (1/1) it does not show the message.

I leave the generated example:

> 0 52 13? * 3/1 * -> At 01:52 PM, every 1 day of the week, Wednesday through Saturday
> 0 52 13? * 2/1 * -> At 01:52 PM, every 1 day of the week, Tuesday through Saturday
> **0 52 13? * 1/1 * -> At 01:52 PM**
> 0 52 13? * 0/1 * -> At 01:52 PM, every 1 day of the week, Sunday through Saturday

**Comment by bradymholt** [comment]
Thanks!  Incoming fix in https://github.com/bradymholt/cRonstrue/pull/116.
