### ISSUE TITLE
An hour of 08 or 09 results in aN in the ouput

### ISSUE THREAD

**Issue by gkankstech** [bradyholt/cRonstrue#12]
Having an hours value of 08 or 09 produces aN in the hours portion of the result.

As an example: 00 08 * * 2
Produces: At aN:00 AM, only on Tuesday

What's odd is if I use the demo website you provide to test that statement it produces the correct result.

I am using cronstrue.min.js from 0.8.0 with this library to execute JS: org.mozilla.javascript

**Comment by gkankstech** [comment]
To clarify an hour value of 8 or 9 is fine. It is when the value has a leading zero (0) that we're seeing the behavior.

**Comment by bradyholt** [comment]
Interesting.  I cannot reproduce this either in Chrome, Firefox, Node 0.10, 4, or 7.  Can you give me more information about your environment?

**Comment by gkankstech** [comment]
I'm using Pentaho Data Integration, an ETL, using the Javascript execution step name "Modified Java Script Value".  I simply place the function in the code box on one line and then call it this way on the next: 

var CronScheduleDesc = cronstrue.toString(FullCronSchedule);

FullCronSchedule is a string containing the value the cron schedule (trimmed for spaces on either side) of each row. So this step is called for each row it finds in the file. I've looked at the data before it enters the step and the data looks proper in that string. 

It's not a big deal, for my use case, as I the behavior is very predictable and I can just have a step farther downstream fix it.

**Comment by bradyholt** [comment]
Oh wow.  Interesting.  Yeah, this seems like a pretty specific use case and is probably an environmental issue.  Good luck!
