### ISSUE TITLE
Get the result as a `Date` object instead of a `string`

### ISSUE THREAD

**Issue by Hywan** [bradyholt/cRonstrue#14]
Hello 😄,

Thank you for your library, very helpful. I have a question though. Is it possible to get a `Date` object instead of a `string`? Looking at the code, it seems not, but it would be very interesting to compute a “next schedule in …” string. Thanks!

**Comment by bradyholt** [comment]
@Hywan Thanks for the feedback!  No, this library doesn't focus on trying to parse and structure the cron schedule in a way that allows you to read the schedule (i.e. "next scheduled time") but rather just on generating a description to describe the schedule itself.  If you look around on npm there might be another package that would do what you are looking for.

**Comment by Hywan** [comment]
Sure, there are plenty, but not with the quality of your library, and not with zero dependency :-). Thanks.

**Comment by bradyholt** [comment]
Zero dependencies FTW!

**Comment by Ramblurr** [comment]
Just chiming in that it would be great if this library, or a sister library allowed to get the "next date times" of the cron. This library is the only one I've found that fully supports quartz' cron style and works reliably.
