### ISSUE TITLE
0 0 * * 0

### ISSUE THREAD

**Issue by michael-smith-tanium** [bradyholt/cRonstrue#21]
Returns
> At 00:00 AM, only on Sunday

00:00 AM is not a valid time, should be 12:00 AM

**Comment by bradyholt** [comment]
I would surely welcome a PR for this 😄

**Comment by michael-smith-tanium** [comment]
I don't see anything like grunt so what is the best way to starting building TS for cRonstrue? Also, how do I run the tests?

Do you have any contributor guidelines?

**Comment by bradyholt** [comment]
@michael-smith-tanium I don't have contributor guidelines yet.  Once you run `npm install`, there are package.json scripts you can use for build/test (build: https://github.com/bradyholt/cRonstrue/blob/master/package.json#L52).  So,

```
npm install
npm run build
npm test
```

**Comment by michael-smith-tanium** [comment]
https://github.com/bradyholt/cRonstrue/pull/22

**Comment by bradyholt** [comment]
Fixed by https://github.com/bradyholt/cRonstrue/pull/22
