### ISSUE TITLE
unreachable code after return statement

### ISSUE THREAD

**Issue by glutaminefree** [bradyholt/cRonstrue#214]
Hi!

I got error

`unreachable code after return statement`

when importing i18n version

`import cronstrue from 'cronstrue/i18n';`

Lib version 1.117.0

**Comment by bradymholt** [comment]
I just checked and am not seeing the same thing and have not heard others hitting this either.  It might be something specific to your environment.

**Comment by engelfranziska** [comment]
The warning is logged in firefox but not in chrome.
The reason is a double return in `sw.ts` function `atX0SecondsPastTheMinute` line 52.  
```
  atX0SecondsPastTheMinute() {
    return "at %s seconds past the minute";
    return "sekunde %s baada ya dakika";
  }
```

**Comment by bradymholt** [comment]
Thanks for tracing it down. Would you be up for submitting a PR?
