### ISSUE TITLE
Last day of the month shows as "L of the month" in lists and intervals

### ISSUE THREAD

**Issue by SavkovCG** [bradyholt/cRonstrue#23]
According to Live Demo:
0 20 L * * = At 08:00 PM, on the last day of the month (OK)
0 20 15,L * * = At 08:00 PM, on day 15 and **L** of the month
0 20 1-10,20-L * * = At 08:00 PM, on day 1 through 10 and 20 through **L** of the month

**Comment by bradyholt** [comment]
Fixed and released as 0.10.8

**Comment by SavkovCG** [comment]
Thanks!
