### ISSUE TITLE
Bug: not human readable

### ISSUE THREAD

**Issue by sanjorgek** [bradyholt/cRonstrue#27]
I got
```bash
> const cronstrue = require('cronstrue');
> cronstrue.toString('0 15 10 * * L')
'At 10:15 AM, on the last undefined of the month'
```

But [Quartz specs](http://www.quartz-scheduler.org/documentation/quartz-1.x/tutorials/crontrigger) says:

- L (“last”) - has different meaning in each of the two fields in which it is allowed. For example, the value “L” in the day-of-month field means “the last day of the month” - day 31 for January, day 28 for February on non-leap years. **If used in the day-of-week field by itself, it simply means “7” or “SAT”.** But if used in the day-of-week field after another value, it means “the last xxx day of the month” - for example “6L” means “the last friday of the month”. When using the ‘L’ option, it is important not to specify lists, or ranges of values, as you’ll get confusing results.

**Comment by bradyholt** [comment]
@sanjorgek Thanks for the report!  Want to take a crack at a PR?

**Comment by bradyholt** [comment]
Fixed and released: https://github.com/bradyholt/cRonstrue/releases/tag/v0.10.9
