### ISSUE TITLE
Break out locales into own JS files for browser

### ISSUE THREAD

**Issue by vonWolfehaus** [bradyholt/cRonstrue#31]
Hey there, thanks for making this fantastic library! I'd like to conditionally load locales based on the user's settings so that those with slower connections don't have to wait for resources they don't need. So could you provide a separate `js` file per locale that automatically adds itself to the library once loaded? Would appreciate this very much!

**Comment by bradyholt** [comment]
@vonWolfehaus Sounds like a nice feature!  I won't have time to tackle this currently so I'd welcome a PR if you want to take a crack at it.

**Comment by bradyholt** [comment]
I'm going to close this for now but I would welcome a PR.
