### ISSUE TITLE
leading 0 not removed

### ISSUE THREAD

**Issue by hverlin** [bradyholt/cRonstrue#33]
Hi,

if there are leading '0' in the cron expression, I expect them to be removed in the description.

Ex: for the input`*/000005 * * * *`, it returns: `Every 000005 minutes` instead of  `Every 5 minutes`

**Comment by bradyholt** [comment]
I'd welcome a PR to fix this but I am going to close this for now as this library is not intended to be a full parser/validator for cron expressions but rather one to describe them, primarily.  Thanks for the report though!
