### ISSUE TITLE
Uncaught Error: DOW part contains invalid values: 'NaN', Error while executing from expression "0 4 * * */2"

### ISSUE THREAD

**Issue by kru032** [bradyholt/cRonstrue#34]
We are getting following error, while retrieving translation.
  | t.getFullDescription | @ | cronstrue.js:141
-- | -- | -- | --
  | t.toString | @ | cronstrue.js:114 

Error seems to be happening while parsing the expression.The expression seems to be having a Nan value.

**Comment by bradyholt** [comment]
I cannot repo this.  If you are still having issues, I would need more info such as version you are using, and a short code sample so I can see how you are attempting to use the library.

![image](https://user-images.githubusercontent.com/759811/31458686-ab447984-ae75-11e7-8441-19925c0b22e5.png)
