### ISSUE TITLE
Expression with multiple days of month with W modifier is not properly translated

### ISSUE THREAD

**Issue by shaddyz** [bradyholt/cRonstrue#5]
Expression: "0 30 14 1W,15W * ? *"
Actual Translation: "At 02:30 PM, on the first weekday of the month"
Expected Translation: "At 02:30 PM, on the first weekday and the weekday nearest day 15 of the month"

**Comment by bradyholt** [comment]
That's for the issue @shaddyz .  Most all of the cron implementations I know of do not support a list or range of values when using the "W" (weekday) specifier.  For example, in EasyCron the docs say "The 'W' character can be specified only when the day-of-month is a single day, not a range or list of days." [https://www.easycron.com/faq/What-cron-expression-does-easycron-support](https://www.easycron.com/faq/What-cron-expression-does-easycron-support) .  Do you know of an implementation of cron which supports something like `0 30 14 1W,15W * ? *`?  Does Quartz?

**Comment by shaddyz** [comment]
So, I found that the validation performed on the expression may lead one to believe it's supported by Quartz even though it may not actually work:
>Note that the validity as checked by this method doesn't guarantee that an expression will work. E.g. isValidExpression("0 0 12 1/2 * MON-FRI *") returns true, but at runtime it throws UnsupportedOperationException: Support for specifying both a day-of-week AND a day-of-month parameter is not implemented.
[http://stackoverflow.com/a/2363119]

I did confirm that Quartz only supports the W modifier when the day of month is a single value:
> The 'W' character can only be specified when the day-of-month is a single day, not a range or list of days.
[http://www.quartz-scheduler.org/api/2.2.1/org/quartz/CronExpression.html]

So, I'd say that the library should probably error out on the expression instead of falsely translating it since 1W,15W is not valid

**Comment by bradyholt** [comment]
Thanks for your help with this @shaddyz - PR here to fix it: https://github.com/bradyholt/cRonstrue/issues/7 .  I've release latest out on npm.

**Comment by shaddyz** [comment]
no problem @bradyholt and thanks for the quick response
