### ISSUE TITLE
Bower usage

### ISSUE THREAD

**Issue by upeshdesai** [bradyholt/cRonstrue#8]
Would it be possible for you to put this up on bower?

**Comment by bradyholt** [comment]
I'm going to pass on publishing to bower since installing from npm is super easy.  If there are a bunch of 👍  added on this issue then I will reconsider.  Thank you for the suggestion.

**Comment by thejavatar** [comment]
Would that be a lot of extra maintenance work for you? In case of our project, all the the libraries we use in the web-application are downloaded using bower. The dependencies coming from node on the other hand are stored in other place and it would be quite hacky to mix both. If this is just one-time job to register it in bower I would be happy to help.

Also, thanks for great library!

**Comment by bradyholt** [comment]
I just went to publish it and it looks like someone else already published the library as "cronstrue" on bower so you can pull it down now.
